# Generated by Django 6.0.6 on 2026-06-13 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='running', max_length=15)),
                ('search_description', models.CharField(max_length=255)),
                ('total_found', models.IntegerField(blank=True, null=True)),
                ('processed_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('logs', models.TextField(blank=True, default='')),
                ('excel_file_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(default='sedan', max_length=50)),
                ('fuel_type', models.CharField(default='dizelov', max_length=50)),
                ('min_price', models.IntegerField(default=5000)),
                ('max_price', models.IntegerField(default=30000)),
                ('min_power', models.IntegerField(default=100)),
                ('max_power', models.IntegerField(default=300)),
                ('max_pages', models.IntegerField(default=20)),
                ('delay', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('production_date', models.CharField(blank=True, max_length=50, null=True)),
                ('price_eur', models.FloatField(blank=True, null=True)),
                ('price_bgn', models.IntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='crawler_ui.crawlsession')),
            ],
        ),
    ]
