# Generated by Django 6.0.6 on 2026-06-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='brand',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='fuel_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='price_bgn',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['-created_at'], name='idx_listing_created'),
        ),
        migrations.AddIndex(
            model_name='carlisting',
            index=models.Index(fields=['brand', 'price_bgn'], name='idx_listing_brand_price'),
        ),
        migrations.AddIndex(
            model_name='crawlsession',
            index=models.Index(fields=['status'], name='idx_session_status'),
        ),
        migrations.AddIndex(
            model_name='crawlsession',
            index=models.Index(fields=['-start_time'], name='idx_session_start'),
        ),
    ]
